// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilUpdatedAt(value *time.Time) *FileUpdate {
	if value != nil {
		return f.SetUpdatedAt(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilUpdatedAt(value *time.Time) *FileUpdateOne {
	if value != nil {
		return f.SetUpdatedAt(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilUpdatedAt(value *time.Time) *FileCreate {
	if value != nil {
		return f.SetUpdatedAt(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilDeleteAt(value *time.Time) *FileUpdate {
	if value != nil {
		return f.SetDeleteAt(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilDeleteAt(value *time.Time) *FileUpdateOne {
	if value != nil {
		return f.SetDeleteAt(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilDeleteAt(value *time.Time) *FileCreate {
	if value != nil {
		return f.SetDeleteAt(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilCode(value *string) *FileUpdate {
	if value != nil {
		return f.SetCode(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilCode(value *string) *FileUpdateOne {
	if value != nil {
		return f.SetCode(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilCode(value *string) *FileCreate {
	if value != nil {
		return f.SetCode(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilName(value *string) *FileUpdate {
	if value != nil {
		return f.SetName(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilName(value *string) *FileUpdateOne {
	if value != nil {
		return f.SetName(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilName(value *string) *FileCreate {
	if value != nil {
		return f.SetName(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilFileType(value *uint8) *FileUpdate {
	if value != nil {
		return f.SetFileType(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilFileType(value *uint8) *FileUpdateOne {
	if value != nil {
		return f.SetFileType(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilFileType(value *uint8) *FileCreate {
	if value != nil {
		return f.SetFileType(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilSize(value *uint64) *FileUpdate {
	if value != nil {
		return f.SetSize(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilSize(value *uint64) *FileUpdateOne {
	if value != nil {
		return f.SetSize(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilSize(value *uint64) *FileCreate {
	if value != nil {
		return f.SetSize(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilPath(value *string) *FileUpdate {
	if value != nil {
		return f.SetPath(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilPath(value *string) *FileUpdateOne {
	if value != nil {
		return f.SetPath(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilPath(value *string) *FileCreate {
	if value != nil {
		return f.SetPath(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilTempPath(value *string) *FileUpdate {
	if value != nil {
		return f.SetTempPath(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilTempPath(value *string) *FileUpdateOne {
	if value != nil {
		return f.SetTempPath(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilTempPath(value *string) *FileCreate {
	if value != nil {
		return f.SetTempPath(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdate) SetNotNilUserID(value *string) *FileUpdate {
	if value != nil {
		return f.SetUserID(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileUpdateOne) SetNotNilUserID(value *string) *FileUpdateOne {
	if value != nil {
		return f.SetUserID(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (f *FileCreate) SetNotNilUserID(value *string) *FileCreate {
	if value != nil {
		return f.SetUserID(*value)
	}
	return f
}

// set field if value's pointer is not nil.
func (t *TagUpdate) SetNotNilUpdatedAt(value *time.Time) *TagUpdate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdateOne) SetNotNilUpdatedAt(value *time.Time) *TagUpdateOne {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagCreate) SetNotNilUpdatedAt(value *time.Time) *TagCreate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdate) SetNotNilDeleteAt(value *time.Time) *TagUpdate {
	if value != nil {
		return t.SetDeleteAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdateOne) SetNotNilDeleteAt(value *time.Time) *TagUpdateOne {
	if value != nil {
		return t.SetDeleteAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagCreate) SetNotNilDeleteAt(value *time.Time) *TagCreate {
	if value != nil {
		return t.SetDeleteAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdate) SetNotNilKey(value *string) *TagUpdate {
	if value != nil {
		return t.SetKey(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdateOne) SetNotNilKey(value *string) *TagUpdateOne {
	if value != nil {
		return t.SetKey(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagCreate) SetNotNilKey(value *string) *TagCreate {
	if value != nil {
		return t.SetKey(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdate) SetNotNilAlias(value *string) *TagUpdate {
	if value != nil {
		return t.SetAlias(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdateOne) SetNotNilAlias(value *string) *TagUpdateOne {
	if value != nil {
		return t.SetAlias(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagCreate) SetNotNilAlias(value *string) *TagCreate {
	if value != nil {
		return t.SetAlias(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdate) SetNotNilColor(value *string) *TagUpdate {
	if value != nil {
		return t.SetColor(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdateOne) SetNotNilColor(value *string) *TagUpdateOne {
	if value != nil {
		return t.SetColor(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagCreate) SetNotNilColor(value *string) *TagCreate {
	if value != nil {
		return t.SetColor(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdate) SetNotNilImageUrl(value *string) *TagUpdate {
	if value != nil {
		return t.SetImageUrl(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagUpdateOne) SetNotNilImageUrl(value *string) *TagUpdateOne {
	if value != nil {
		return t.SetImageUrl(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TagCreate) SetNotNilImageUrl(value *string) *TagCreate {
	if value != nil {
		return t.SetImageUrl(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilUpdatedAt(value *time.Time) *UserUpdate {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilUpdatedAt(value *time.Time) *UserUpdateOne {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilUpdatedAt(value *time.Time) *UserCreate {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilDeleteAt(value *time.Time) *UserUpdate {
	if value != nil {
		return u.SetDeleteAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilDeleteAt(value *time.Time) *UserUpdateOne {
	if value != nil {
		return u.SetDeleteAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilDeleteAt(value *time.Time) *UserCreate {
	if value != nil {
		return u.SetDeleteAt(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilName(value *string) *UserUpdate {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilName(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilName(value *string) *UserCreate {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilEmail(value *string) *UserUpdate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilEmail(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilEmail(value *string) *UserCreate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilPassword(value *string) *UserUpdate {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilPassword(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilPassword(value *string) *UserCreate {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}
