// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZooLearn/zoo/ent/predicate"
	"github.com/ZooLearn/zoo/ent/tag"
)

// TagUpdate is the builder for updating Tag entities.
type TagUpdate struct {
	config
	hooks    []Hook
	mutation *TagMutation
}

// Where appends a list predicates to the TagUpdate builder.
func (tu *TagUpdate) Where(ps ...predicate.Tag) *TagUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TagUpdate) SetUpdatedAt(t time.Time) *TagUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetDeleteAt sets the "delete_at" field.
func (tu *TagUpdate) SetDeleteAt(t time.Time) *TagUpdate {
	tu.mutation.SetDeleteAt(t)
	return tu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (tu *TagUpdate) SetNillableDeleteAt(t *time.Time) *TagUpdate {
	if t != nil {
		tu.SetDeleteAt(*t)
	}
	return tu
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (tu *TagUpdate) ClearDeleteAt() *TagUpdate {
	tu.mutation.ClearDeleteAt()
	return tu
}

// SetKey sets the "key" field.
func (tu *TagUpdate) SetKey(s string) *TagUpdate {
	tu.mutation.SetKey(s)
	return tu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (tu *TagUpdate) SetNillableKey(s *string) *TagUpdate {
	if s != nil {
		tu.SetKey(*s)
	}
	return tu
}

// SetAlias sets the "alias" field.
func (tu *TagUpdate) SetAlias(s string) *TagUpdate {
	tu.mutation.SetAlias(s)
	return tu
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (tu *TagUpdate) SetNillableAlias(s *string) *TagUpdate {
	if s != nil {
		tu.SetAlias(*s)
	}
	return tu
}

// SetColor sets the "color" field.
func (tu *TagUpdate) SetColor(s string) *TagUpdate {
	tu.mutation.SetColor(s)
	return tu
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (tu *TagUpdate) SetNillableColor(s *string) *TagUpdate {
	if s != nil {
		tu.SetColor(*s)
	}
	return tu
}

// SetImageUrl sets the "imageUrl" field.
func (tu *TagUpdate) SetImageUrl(s string) *TagUpdate {
	tu.mutation.SetImageUrl(s)
	return tu
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (tu *TagUpdate) SetNillableImageUrl(s *string) *TagUpdate {
	if s != nil {
		tu.SetImageUrl(*s)
	}
	return tu
}

// Mutation returns the TagMutation object of the builder.
func (tu *TagUpdate) Mutation() *TagMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TagUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TagUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TagUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TagUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TagUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := tag.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TagUpdate) check() error {
	if v, ok := tu.mutation.Key(); ok {
		if err := tag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Tag.key": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Alias(); ok {
		if err := tag.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Tag.alias": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Color(); ok {
		if err := tag.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Tag.color": %w`, err)}
		}
	}
	return nil
}

func (tu *TagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tag.Table, tag.Columns, sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(tag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.DeleteAt(); ok {
		_spec.SetField(tag.FieldDeleteAt, field.TypeTime, value)
	}
	if tu.mutation.DeleteAtCleared() {
		_spec.ClearField(tag.FieldDeleteAt, field.TypeTime)
	}
	if value, ok := tu.mutation.Key(); ok {
		_spec.SetField(tag.FieldKey, field.TypeString, value)
	}
	if value, ok := tu.mutation.Alias(); ok {
		_spec.SetField(tag.FieldAlias, field.TypeString, value)
	}
	if value, ok := tu.mutation.Color(); ok {
		_spec.SetField(tag.FieldColor, field.TypeString, value)
	}
	if value, ok := tu.mutation.ImageUrl(); ok {
		_spec.SetField(tag.FieldImageUrl, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TagUpdateOne is the builder for updating a single Tag entity.
type TagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TagMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TagUpdateOne) SetUpdatedAt(t time.Time) *TagUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetDeleteAt sets the "delete_at" field.
func (tuo *TagUpdateOne) SetDeleteAt(t time.Time) *TagUpdateOne {
	tuo.mutation.SetDeleteAt(t)
	return tuo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableDeleteAt(t *time.Time) *TagUpdateOne {
	if t != nil {
		tuo.SetDeleteAt(*t)
	}
	return tuo
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (tuo *TagUpdateOne) ClearDeleteAt() *TagUpdateOne {
	tuo.mutation.ClearDeleteAt()
	return tuo
}

// SetKey sets the "key" field.
func (tuo *TagUpdateOne) SetKey(s string) *TagUpdateOne {
	tuo.mutation.SetKey(s)
	return tuo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableKey(s *string) *TagUpdateOne {
	if s != nil {
		tuo.SetKey(*s)
	}
	return tuo
}

// SetAlias sets the "alias" field.
func (tuo *TagUpdateOne) SetAlias(s string) *TagUpdateOne {
	tuo.mutation.SetAlias(s)
	return tuo
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableAlias(s *string) *TagUpdateOne {
	if s != nil {
		tuo.SetAlias(*s)
	}
	return tuo
}

// SetColor sets the "color" field.
func (tuo *TagUpdateOne) SetColor(s string) *TagUpdateOne {
	tuo.mutation.SetColor(s)
	return tuo
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableColor(s *string) *TagUpdateOne {
	if s != nil {
		tuo.SetColor(*s)
	}
	return tuo
}

// SetImageUrl sets the "imageUrl" field.
func (tuo *TagUpdateOne) SetImageUrl(s string) *TagUpdateOne {
	tuo.mutation.SetImageUrl(s)
	return tuo
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableImageUrl(s *string) *TagUpdateOne {
	if s != nil {
		tuo.SetImageUrl(*s)
	}
	return tuo
}

// Mutation returns the TagMutation object of the builder.
func (tuo *TagUpdateOne) Mutation() *TagMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TagUpdate builder.
func (tuo *TagUpdateOne) Where(ps ...predicate.Tag) *TagUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TagUpdateOne) Select(field string, fields ...string) *TagUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tag entity.
func (tuo *TagUpdateOne) Save(ctx context.Context) (*Tag, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TagUpdateOne) SaveX(ctx context.Context) *Tag {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TagUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TagUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TagUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := tag.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TagUpdateOne) check() error {
	if v, ok := tuo.mutation.Key(); ok {
		if err := tag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Tag.key": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Alias(); ok {
		if err := tag.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Tag.alias": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Color(); ok {
		if err := tag.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Tag.color": %w`, err)}
		}
	}
	return nil
}

func (tuo *TagUpdateOne) sqlSave(ctx context.Context) (_node *Tag, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tag.Table, tag.Columns, sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tag.FieldID)
		for _, f := range fields {
			if !tag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(tag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.DeleteAt(); ok {
		_spec.SetField(tag.FieldDeleteAt, field.TypeTime, value)
	}
	if tuo.mutation.DeleteAtCleared() {
		_spec.ClearField(tag.FieldDeleteAt, field.TypeTime)
	}
	if value, ok := tuo.mutation.Key(); ok {
		_spec.SetField(tag.FieldKey, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Alias(); ok {
		_spec.SetField(tag.FieldAlias, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Color(); ok {
		_spec.SetField(tag.FieldColor, field.TypeString, value)
	}
	if value, ok := tuo.mutation.ImageUrl(); ok {
		_spec.SetField(tag.FieldImageUrl, field.TypeString, value)
	}
	_node = &Tag{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
